name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following info:
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is.
      placeholder: Something broke when...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please list the steps to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Kotlin version, etc.
      placeholder: Ubuntu 22.04, Kotlin 1.9.0
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
