package org.kisu.units.electromagnetic

import org.kisu.units.Measure
import org.kisu.units.base.Metre
import org.kisu.units.representation.Quotient
import org.kisu.units.special.Coulomb
import java.math.BigDecimal

/**
 * Represents the SI unit **coulomb per metre (C/m)**.
 *
 * This unit measures **linear charge density**, i.e., the amount of electric
 * charge distributed per unit length.
 * It is defined as the [Quotient] of [Coulomb] (electric charge) and [Metre] (length).
 *
 * Example usages include:
 * - Describing charge along wires, filaments, or rods
 * - Calculating electric fields from line charge distributions
 *
 * @see LinearChargeDensity for the physical quantity represented by this unit.
 */
typealias CoulombPerMetre = Quotient<Coulomb, Metre>

/**
 * Represents **linear charge density** (λ), which is the amount of electric charge
 * distributed per unit length of a line.
 *
 * - **Dimension**: electric charge per length (C/m)
 * - **SI Unit**: coulomb per metre (C/m)
 *
 * Linear charge density is used to describe charge distributions along
 * one-dimensional objects such as **wires, filaments, or charged rods**.
 * It plays a key role in **electrostatics** when calculating electric fields
 * and potentials generated by line charges using Coulomb's law or Gauss's law.
 *
 * @param magnitude numerical value of the measure
 * @param expression unit expression in coulomb per metre (C/m)
 */
class LinearChargeDensity(
    magnitude: BigDecimal,
    expression: CoulombPerMetre
) : Measure<CoulombPerMetre, LinearChargeDensity>(magnitude, expression, ::LinearChargeDensity)
